/*
 * Tatum API Reference
 *
 * # Welcome to the Tatum API Reference!  ## What is Tatum? ## What is Tatum?  Tatum offers a flexible framework to build, run, and scale blockchain apps fast. To learn more about the Tatum blockchain development framework, visit [our website](https://tatum.io/framework).  The Tatum API features powerful endpoints that simplify a complex blockchain into single API requests. Code for all supported blockchains using unified API calls.  ## Need help?  To chat with other developers, get help from the Support team, and engage with the thriving Tatum community, join  our [Discord server](https://discord.com/invite/tatum). For more information about how to work with Tatum, review the [online documentation](https://docs.tatum.io/).  ## About this API Reference  The Tatum API Reference is based on OpenAPI Specification v3.1.0 with a few [vendor extensions](https://github.com/Redocly/redoc/blob/master/docs/redoc-vendor-extensions.md) applied.  # Authentication  When using the Tatum API, you authenticate yourself with an **API key**. <SecurityDefinitions /> 
 *
 * API version: 3.16.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package tatum

type WebHook struct {
	// Type of the subscription.
	Type_ string `json:"type"`
	// ID of the WebHook
	Id string `json:"id"`
	// ID of the subscription
	SubscriptionId string `json:"subscriptionId"`
	// ID of the subscription
	Url string `json:"url"`
	// Data of webhook
	Data *interface{} `json:"data"`
	// Next webhook execution try time
	NextTime float64 `json:"nextTime,omitempty"`
	// Webhook execution time
	Timestamp float64 `json:"timestamp,omitempty"`
	// Number
	RetryCount float64 `json:"retryCount,omitempty"`
	// Flag indicating whether this webhook was successful or not
	Failed bool `json:"failed"`
	Response *WebHookResponse `json:"response"`
}
