/*
 * Tatum API Reference
 *
 * # Welcome to the Tatum API Reference!  ## What is Tatum? ## What is Tatum?  Tatum offers a flexible framework to build, run, and scale blockchain apps fast. To learn more about the Tatum blockchain development framework, visit [our website](https://tatum.io/framework).  The Tatum API features powerful endpoints that simplify a complex blockchain into single API requests. Code for all supported blockchains using unified API calls.  ## Need help?  To chat with other developers, get help from the Support team, and engage with the thriving Tatum community, join  our [Discord server](https://discord.com/invite/tatum). For more information about how to work with Tatum, review the [online documentation](https://docs.tatum.io/).  ## About this API Reference  The Tatum API Reference is based on OpenAPI Specification v3.1.0 with a few [vendor extensions](https://github.com/Redocly/redoc/blob/master/docs/redoc-vendor-extensions.md) applied.  # Authentication  When using the Tatum API, you authenticate yourself with an **API key**. <SecurityDefinitions /> 
 *
 * API version: 3.16.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package tatum

type TransferTronMnemonic struct {
	// Blockchain address to send assets
	Address string `json:"address"`
	// Amount to be sent in Tron.
	Amount string `json:"amount"`
	// Compliance check, if withdrawal is not compliant, it will not be processed.
	Compliant bool `json:"compliant,omitempty"`
	// Fee to be submitted as a transaction fee to blockchain. If none is set, default value of 2.5 TRX is used.
	Fee string `json:"fee,omitempty"`
	// Derivation index of sender address.
	Index int32 `json:"index"`
	// Mnemonic to generate private key for sender address. Either mnemonic and index, privateKey or signature Id must be present - depends on the type of account and xpub.
	Mnemonic string `json:"mnemonic"`
	// Identifier of the payment, shown for created Transaction within Tatum sender account.
	PaymentId string `json:"paymentId,omitempty"`
	// Sender account ID
	SenderAccountId string `json:"senderAccountId"`
	// Note visible to owner of withdrawing account
	SenderNote string `json:"senderNote,omitempty"`
}
